"""init

Revision ID: 2f37076d4135
Revises: 
Create Date: 2026-01-01 13:06:43.399500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f37076d4135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('super_cat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_super_cat_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('product_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('super_cat_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['super_cat_id'], ['super_cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_lines_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_lines_super_cat_id'), ['super_cat_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_line_id'], ['product_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_categories_product_line_id'), ['product_line_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cash_price', sa.Numeric(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=True)

    op.create_table('cex_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cex_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cex_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cex_products_cex_id'), ['cex_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cex_products_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cex_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cex_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_cex_products_cex_id'))

    op.drop_table('cex_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))

    op.drop_table('products')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_product_line_id'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_lines_super_cat_id'))
        batch_op.drop_index(batch_op.f('ix_product_lines_name'))

    op.drop_table('product_lines')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('super_cat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_super_cat_name'))

    op.drop_table('super_cat')
    # ### end Alembic commands ###
